#!/bin/bash

RCM_EXTENSION_VERSION=0.0.2-alpha.1

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm obfuscate-proxy run ssh-server

Options:
   --listen-port=[PORT]
        Set the port.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --listen-port=*) listen_port="${1#*=}"; shift ;;
        --listen-port) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then listen_port="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Require.
require vendor/ijortengab/bash/functions/array-search.sh

# ------------------------------------------------------------------------------

# Title.
title rcm obfuscate-proxy run ssh-server
____

# Dependency.
require command systemctl
require command netstat
require command lsof
require command obfs4proxy
require command adduser

# Require, validate, and populate value.
chapter Variable dump.
if [ -z "$listen_port" ];then
    listen_port=2222
fi
code 'listen_port="'$listen_port'"'
____

found=1
user=obfs4-ssh
user_home=/var/lib/obfs4proxy-ssh/
user_gecos="obfs4proxy for ssh"
# todo, buat juga untuk VPN
chapter Mengecek PHP-FPM User.
code id -u '"'$user'"'
if id "$user" >/dev/null 2>&1; then
	__ User '`'$user'`' found.
else
	__ User '`'$user'`' not found.;
	found=
fi
____

if [ -z "$found" ];then
    chapter Membuat Unix user.
	code adduser --system --group --shell '"'/usr/sbin/nologin'"' \
		--home '"'$user_home'"' \
		--gecos '"'$user_gecos'"' \
		$user
	adduser --system --group --shell "/usr/sbin/nologin" \
		--home "$user_home" \
		--gecos "$user_gecos" \
		$user
    ____
fi

chapter Mendeteksi command yang menggunakan port $listen_port.
code 'lsof -i :'$listen_port
lsof -i :$listen_port

_commands_of_port=()
while IFS= read -r line; do
	if [ -n "$line" ];then
		_command=$(ps -p $line -o comm -h)
		if ! ArraySearch "$_command" _commands_of_port[@];then
			_commands_of_port+=("$_command")
		fi
	fi
done <<< `lsof -i :$listen_port -t`
if [ "${#_commands_of_port[@]}" -gt 0 ];then
    __ Command ditemukan:
	for each in "${_commands_of_port[@]}"; do
		__ "$each"
	done

fi
found=
if ArraySearch obfs4proxy _commands_of_port[@];then
    found=1
    __ Command obfs4proxy sudah berjalan dan mendengar port ${listen_port}.
fi
____

if [ -z "$found" ];then
    if [ "${#_commands_of_port[@]}" -gt 0 ];then
        error Terdapat process lain yang sedang me-listen port $listen_port.
        _ Command untuk memaksa mematikan proses yang me-listen port $listen_port:; _.
        code "kill -9 \$(lsof -i :$listen_port -t)"
        while IFS= read -r line; do
            if [ -n "$line" ];then
                _ kill -9 $line; _.
            fi
        done <<< `lsof -i :$listen_port -t`
        x
    fi

    sudo -u obfs4-ssh \
    env TOR_PT_MANAGED_TRANSPORT_VER="1" \
        TOR_PT_STATE_LOCATION="/var/lib/obfs4proxy-ssh/" \
        TOR_PT_SERVER_TRANSPORTS="obfs4" \
        TOR_PT_SERVER_BINDADDR="obfs4-0.0.0.0:${listen_port}" \
        TOR_PT_ORPORT="127.0.0.1:22" \
    obfs4proxy -enableLogging -logLevel DEBUG &
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --listen-port
# )
# FLAG_VALUE=(
# )
# EOF
# clear
